# Generated by Django 4.2.6 on 2023-12-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('fullname', models.CharField(max_length=40)),
                ('peo', models.CharField(max_length=40)),
            ],
        ),
    ]
